language: node_js
node_js:
  - '0.10'

install:
  # - npm config set registry http://23.251.144.68
  # Disable the spinner, it looks bad on Travis
  - 'npm config set spin false'
  # Log HTTP requests
  - 'npm config set loglevel http'
  - 'time npm install'

before_script:
  - 'npm install -g bower grunt-cli'
  #- 'bower install'

script:
  - 'grunt release'